// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB14rPzNrGof0asbsPUt-sU4GREbu7rUyQ',
    appId: '1:203848915104:web:9dc781917e19356af0d1c5',
    messagingSenderId: '203848915104',
    projectId: 'rent-a-ride-c9af8',
    authDomain: 'rent-a-ride-c9af8.firebaseapp.com',
    storageBucket: 'rent-a-ride-c9af8.appspot.com',
    measurementId: 'G-8RW3HCSQQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvHDBaVA2WG-1yNPp5VquZkK0uLfC55BM',
    appId: '1:203848915104:android:d6c281b3a03e237df0d1c5',
    messagingSenderId: '203848915104',
    projectId: 'rent-a-ride-c9af8',
    storageBucket: 'rent-a-ride-c9af8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyYP1VQVviuspOiCgeq7d61olGnm96Jng',
    appId: '1:203848915104:ios:009be08d8ad2a23ff0d1c5',
    messagingSenderId: '203848915104',
    projectId: 'rent-a-ride-c9af8',
    storageBucket: 'rent-a-ride-c9af8.appspot.com',
    iosBundleId: 'com.example.rentcartest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyYP1VQVviuspOiCgeq7d61olGnm96Jng',
    appId: '1:203848915104:ios:9070024b5250e41df0d1c5',
    messagingSenderId: '203848915104',
    projectId: 'rent-a-ride-c9af8',
    storageBucket: 'rent-a-ride-c9af8.appspot.com',
    iosBundleId: 'com.example.rentcartest.RunnerTests',
  );
}
